[project]
name = "sc1008"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "clang-format>=21.1.8",
    "mkdocs-material>=9.7.1",
]
